version: 0.0
os: linux
files:
  - source: webapp-sample/
    destination: /var/www/html/
    overwrite: true
file_exists_behavior: OVERWRITE
branch_config:
  main:
    dev:
      deploymentGroupName: DevGroup
      deploymentGroupConfig:
        serviceRoleArn: arn:aws:iam::099269900176:role/CodedeployCustomRole
    test:
      deploymentGroupName: TestDeploymentGroup
      deploymentGroupConfig:
        serviceRoleArn: arn:aws:iam::ACCOUND_ID:role/CodeDeployTestApplication
    prod:
      deploymentGroupName: ProdDeploymentGroup
      deploymentGroupConfig:
        serviceRoleArn: arn:aws:iam::ACCOUND_ID:role/CodeDeployProdApplication



     

      

            




            
